name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]  # main 브랜치에 push될 때 실행
  pull_request:
    types: [closed]     # PR이 닫힐 때
    branches: [ main ]  # main 브랜치로의 PR일 때

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./CoinBot/gradlew

      - name: Build with Gradle
        run: ./CoinBot/gradlew clean bootJar

      # 빌드된 JAR 파일 확인
      - name: List build directory
        run: ls -la ./CoinBot/build/libs

      # EC2 서버에 SSH 접속하기 위한 키 파일 생성
      - name: Create SSH Directory
        run: mkdir -p ~/.ssh

      - name: Add SSH Key
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem

      # EC2 서버에 JAR 파일 전송 및 배포
      - name: Deploy to EC2
        run: |
          # SSH 연결시 호스트 키 검증 건너뛰기
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

          # 기존 JAR 프로세스 종료
          ssh -i ~/.ssh/key.pem ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} "
            echo 'Stopping existing coin-0.0.1-SNAPSHOT.jar process...';
            PID=\$(pgrep -f 'coin-0.0.1-SNAPSHOT.jar');
            if [ -n \"\$PID\" ]; then
              echo 'Found process with PID: \$PID. Terminating...';
              kill -9 \$PID;
            else
              echo 'No running process found for coin-0.0.1-SNAPSHOT.jar.';
            fi
          "

          # JAR 파일 전송 전 디렉토리 생성
          ssh -i ~/.ssh/key.pem ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} "mkdir -p ~/CoinBot/build/libs"

          # EC2로 JAR 파일 전송
          scp -i ~/.ssh/key.pem \
            ./CoinBot/build/libs/*.jar \
            ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }}:~/CoinBot/build/libs/

          # 배포 스크립트 실행
          ssh -i ~/.ssh/key.pem ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }} \
            "chmod +x ~/CoinBot/script/deploy.sh && ~/CoinBot/script/deploy.sh"
